version: '3'
services:
  alpha_keycapsets:
    build: .
    networks:
      - traefik
    ports:
      - '3001:3001'
    labels:
      - 'traefik.enable=true'
      - 'traefik.backend=alpha_keycapsets'
      - 'traefik.frontend.rule=Host:testing.keycapsets.com'
      - 'traefik.port=3001'

networks:
  traefik:
    external:
      name: docker_default
