version: '3'
services:
    keycapsets:
        build: .
        networks:
            - traefik
        ports:
            - '3001:3001'
        labels:
            - 'traefik.enable=true'
            - 'traefik.backend=keycapsets'
            - 'traefik.frontend.rule=Host:keycapsets.com,www.keycapsets.com'
            - 'traefik.port=3000'
networks:
    traefik:
        external:
            name: docker_default
