version: '3'
services:
    keycapsets:
        environment:
            NODE_ENV: production
        image: ghcr.io/noudadrichem/keycapsets.com:latest
        ports:
            - '3000:3000'
        logging:
            driver: none
        networks:
            - traefik
        labels:
            - 'traefik.enable=true'
            - 'traefik.backend=keycapsets'
            - 'traefik.frontend.rule=Host:keycapsets.com,www.keycapsets.com'
            - 'traefik.port=3000'
networks:
    traefik:
        external:
            name: docker_default
